name: Export files

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amrit3701/freecad-cli:1.0.2-amd64-ubuntu22.04-py3.11-qt5

    steps:
      - name: install nodejs
        run: |
          apt update
          apt install curl -y
          curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
          apt-get install -y nodejs
          # apt install xvfb -y

      - name: Checkout code
        uses: actions/checkout@v4

    
      - name: Run FreeCAD
        run: |
            mkdir /tmp/mirte-frame
            cp -r ./freecadFiles /tmp/mirte-frame
            cp -r ./fonts /tmp/mirte-frame
            cp -r ./scripts /tmp/mirte-frame
            cp ./bill_of_materials.md /tmp/mirte-frame
            cd /tmp/mirte-frame/scripts
            echo "exec(open(\"/tmp/mirte-frame/scripts/generate.py\").read())" | FreeCADCmd
      - name: Upload DXF
        uses: actions/upload-artifact@v4
        with:
          name: dxfs
          path: /tmp/mirte-frame/build/dxf/*
      - name: Upload STL
        uses: actions/upload-artifact@v4
        with:
          name: stls
          path: /tmp/mirte-frame/build/stl/*
      - name: Upload STEP
        uses: actions/upload-artifact@v4
        with:
          name: steps
          path: /tmp/mirte-frame/build/step/*
      - name: zip files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd /tmp/mirte-frame/build
          zip -r /tmp/mirte-frame-stl.zip ./stl/*
          zip -r /tmp/mirte-frame-dxf.zip ./dxf/*
          zip -r /tmp/mirte-frame-step.zip ./step/*
      - name: Push to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
              /tmp/mirte-frame-dxf.zip
              /tmp/mirte-frame-stl.zip
              /tmp/mirte-frame-step.zip
              /tmp/mirte-frame/bill_of_materials.md

